# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 03:56
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('no_of_copies', models.IntegerField(default=5)),
                ('summary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Issued', 'Issued')], max_length=50)),
                ('issue_date', models.DateField(default=datetime.datetime.today)),
                ('return_date', models.DateField(default=app.models.get_deadline)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('typeuser', models.CharField(choices=[('student', 'student'), ('librarian', 'librarian')], max_length=50)),
            ],
        ),
    ]
