# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_table',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='issue_table',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
