# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180719_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_table',
            name='issue_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='issue_table',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
