# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180721_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Issued', 'Issued')], max_length=50)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
