# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-23 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_return_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_history_ReturnedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
