# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-23 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_history_returnedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_history_returnedbooks',
            name='student_name',
        ),
    ]
